name: "Download SDL2_image"
description: "Download SDL2_image sources and binaries for Windows, using MSVC."

branding:
  icon: "download"
  color: "green"

inputs:
  version:
    description: "The version of SDL2_image that will be downloaded"
    required: false
    default: 2.0.5

  sources_destination:
    description: "Where the SDL2_image sources will be saved"
    required: true

  binaries_destination:
    description: "Where the SDL2_image runtime binaries will be saved"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download sources
      shell: powershell
      run: Invoke-WebRequest -Uri "https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-${{inputs.version}}-VC.zip" `
                             -OutFile ${{inputs.sources_destination}}/SDL2_image-devel-${{inputs.version}}-VC.zip

    - name: Unzip sources
      shell: cmd
      run: |
        cd ${{inputs.sources_destination}}
        7z x -y SDL2_image-devel-${{inputs.version}}-VC.zip
        del SDL2_image-devel-${{inputs.version}}-VC.zip

    - name: Download runtime binaries
      run: Invoke-WebRequest -Uri "https://www.libsdl.org/projects/SDL_image/release/SDL2_image-${{inputs.version}}-win32-x64.zip" `
                             -OutFile ${{inputs.binaries_destination}}/SDL2_image-${{inputs.version}}-win32-x64.zip
      shell: powershell

    - name: Unzip runtime binaries archive
      shell: cmd
      run: |
        cd ${{inputs.binaries_destination}}
        7z x -y SDL2_image-${{inputs.version}}-win32-x64.zip
        del SDL2_image-${{inputs.version}}-win32-x64.zip
