name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make directories
        run: mkdir bin
        shell: cmd

      - name: Download SDL2
        uses: albin-johansson/download-sdl2-image@v0.1
        with:
          version: 2.0.5
          sources_destination: .
          binaries_destination: bin
